<?php
class JConfig {
	public $offline = '0';
	public $offline_message = 'This site is down for maintenance.<br /> Please check back again soon.';
	public $display_offline_message = '1';
	public $offline_image = '';
	public $sitename = '=== JD101 ===';
	public $editor = 'tinymce';
	public $captcha = '0';
	public $list_limit = '20';
	public $access = '1';
	public $debug = '0';
	public $debug_lang = '0';
	public $dbtype = 'mysqli';
	public $host = 'localhost';
	public $user = 'root';
	public $password = '';
	public $db = 'joomla-cms_staging_JBS_Brochure_JD101';
	public $dbprefix = 'kodfj_';
	public $live_site = '';
	public $secret = 'qheOV6Zw2GGHQKis';
	public $gzip = '0';
	public $error_reporting = 'default';
	public $helpurl = 'http://help.joomla.org/proxy/index.php?option=com_help&amp;keyref=Help{major}{minor}:{keyref}';
	public $ftp_host = '';
	public $ftp_port = '';
	public $ftp_user = '';
	public $ftp_pass = '';
	public $ftp_root = '';
	public $ftp_enable = '';
	public $offset = 'UTC';
	public $mailonline = '1';
	public $mailer = 'smtp';
	public $mailfrom = 'support@puma-it.com';
	public $fromname = '=== JBS Staging ===';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = '1';
	public $smtpuser = 'principal@puma-it.com';
	public $smtppass = 'Lunasa0811';
	public $smtphost = 'mail.gandi.net';
	public $smtpsecure = 'tls';
	public $smtpport = '587';
	public $caching = '0';
	public $cache_handler = 'file';
	public $cachetime = '15';
	public $MetaDesc = '';
	public $MetaKeys = '';
	public $MetaTitle = '1';
	public $MetaAuthor = '1';
	public $MetaVersion = '0';
	public $robots = '';
	public $sef = '1';
	public $sef_rewrite = '0';
	public $sef_suffix = '0';
	public $unicodeslugs = '0';
	public $feed_limit = '10';
	public $log_path = '/Applications/XAMPP/xamppfiles/htdocs/XAMPP183/joomla-cms/logs';
	public $tmp_path = '/Applications/XAMPP/xamppfiles/htdocs/XAMPP183/joomla-cms/tmp';
	public $lifetime = '15';
	public $session_handler = 'database';
}